import { describe, expect, it } from 'vitest'
import { ATTRIBUTION_RULES, findAttribution, isAllowedAuthorEmail, main } from '../commits.mjs'

// Fixtures are assembled at runtime, so this file never contains a literal trailer or
// generated-with line that a scan of the repo text would flag (P40).
const join = (...parts) => parts.join('')
const name = (...parts) => parts.join('')
const trailer = (who) => join('Co-', 'Authored-By: ', who)
const assistant = name('Cl', 'aude')
const vendor = name('Anth', 'ropic')
const noreply = join('noreply@', vendor.toLowerCase(), '.com')
const robot = String.fromCodePoint(0x1f916)

function fakeIo() {
  const out = { stdout: '', stderr: '' }
  return {
    out,
    io: {
      stdout: { write: (s) => (out.stdout += s) },
      stderr: { write: (s) => (out.stderr += s) },
    },
  }
}

const rulesOf = (text) => findAttribution(text).map((f) => f.rule)

describe('attribution rules', () => {
  it('covers the four documented rules', () => {
    expect(ATTRIBUTION_RULES.map((r) => r.name)).toEqual([
      'co-authored-by-assistant',
      'assistant-noreply-address',
      'generated-with-assistant',
      'robot-emoji',
    ])
  })

  it.each([
    name('cl', 'aude'),
    name('an', 'thropic'),
    name('open', 'ai'),
    name('chat', 'gpt'),
    name('co', 'pilot'),
    name('gem', 'ini'),
    name('cur', 'sor'),
    name('co', 'dex'),
  ])('flags a co-author trailer naming %s (any case)', (who) => {
    expect(
      rulesOf(join('feat: x\n\n', trailer(`${who.toUpperCase()} Bot <bot@example.com>`))),
    ).toContain('co-authored-by-assistant')
    expect(rulesOf(trailer(`${who} <x@example.com>`).toLowerCase())).toContain(
      'co-authored-by-assistant',
    )
  })

  it('flags the assistant noreply address anywhere', () => {
    expect(findAttribution(join('body\n', trailer(`${assistant} Opus <${noreply}>`)))).toEqual([
      { line: 2, rule: 'assistant-noreply-address' },
      { line: 2, rule: 'co-authored-by-assistant' },
    ])
  })

  it.each([
    join('Generated with [', assistant, ' Code](https://example.com/x)'),
    join('generated by ', name('Chat', 'GPT')),
    join('This file was generated by our internal tool using ', name('Gem', 'ini')),
    join('Generated with an ', name('LL', 'M')),
    join('generated by ', name('A', 'I')),
    join('Generated with\n', assistant),
  ])('flags the generated-with line %j', (text) => {
    expect(rulesOf(text)).toContain('generated-with-assistant')
  })

  it('flags the robot-face emoji', () => {
    expect(findAttribution(join('Summary ', robot, ' done'))).toEqual([
      { line: 1, rule: 'robot-emoji' },
    ])
  })

  it.each([
    'feat: add generated database types',
    join('Personal day planner with a ', assistant, ' MCP connector'),
    'docs: plan the MCP server so the assistant can plan my day',
    trailer('Jane Doe <jane@example.com>'),
    'Generated by the Supabase CLI from the linked project schema',
    'generated by airflow scheduler',
    'maintain the said rules; detail the retail email',
  ])('does not flag %j', (text) => {
    expect(findAttribution(text)).toEqual([])
  })
})

describe('author e-mail allowlist', () => {
  it.each([
    ['karthi.ai.engineer@gmail.com', true],
    ['Karthi.AI.Engineer@Gmail.com', true],
    ['123456+karthi-ai-engineer@users.noreply.github.com', true],
    ['49699333+dependabot[bot]@users.noreply.github.com', true],
    ['github-actions[bot]@users.noreply.github.com', true],
    ['someone@example.com', false],
    ['karthi-ai-engineer@users.noreply.github.com', false],
    ['123+someone-else@users.noreply.github.com', false],
    ['', false],
  ])('%j allowed: %s', (email, allowed) => {
    expect(isAllowedAuthorEmail(email)).toBe(allowed)
  })
})

describe('main', () => {
  it('says the PR text was not provided and still checks the commit range', () => {
    const { io, out } = fakeIo()
    expect(main(['--range', 'HEAD..HEAD'], io, { PR_TITLE: '', PR_BODY: '' })).toBe(0)
    expect(out.stdout).toContain('PR text: not provided (push event or bot-authored PR)')
    expect(out.stdout).toContain('commits: 0 in HEAD..HEAD checked (messages and author e-mails)')
  })

  it('checks the PR title and body when they are set', () => {
    const { io, out } = fakeIo()
    const env = { PR_TITLE: 'feat: add planner', PR_BODY: join('Summary\n\n', trailer(assistant)) }
    expect(main(['--range', 'HEAD..HEAD'], io, env)).toBe(1)
    expect(out.stdout).toContain('ATTRIBUTION PR body:3 matches co-authored-by-assistant')
    expect(out.stdout).not.toContain('PR text: not provided')
  })

  it('rejects unknown arguments', () => {
    const { io, out } = fakeIo()
    expect(main(['--nope'], io, {})).toBe(1)
    expect(out.stderr).toMatch(/unexpected argument/)
  })
})
