import {
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Car,
  Code,
  Coffee,
  Dog,
  Droplets,
  Dumbbell,
  Flame,
  Footprints,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  House,
  Laptop,
  Leaf,
  ListTodo,
  Mail,
  MessageCircle,
  Moon,
  Music,
  Palette,
  PenLine,
  Phone,
  Pill,
  Plane,
  Presentation,
  Shirt,
  ShoppingCart,
  ShowerHead,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Target,
  Timer,
  Users,
  Utensils,
  Video,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { cn } from '@/lib/utils'

/** Icons offered in the picker, keyed by the name stored in `tasks.icon`. */
export const TASK_ICONS: Readonly<Record<string, LucideIcon>> = {
  'list-todo': ListTodo,
  sunrise: Sunrise,
  sun: Sun,
  sunset: Sunset,
  moon: Moon,
  bed: Bed,
  coffee: Coffee,
  utensils: Utensils,
  'shower-head': ShowerHead,
  shirt: Shirt,
  laptop: Laptop,
  code: Code,
  briefcase: Briefcase,
  presentation: Presentation,
  users: Users,
  'message-circle': MessageCircle,
  phone: Phone,
  mail: Mail,
  video: Video,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'pen-line': PenLine,
  brain: Brain,
  target: Target,
  timer: Timer,
  dumbbell: Dumbbell,
  footprints: Footprints,
  bike: Bike,
  heart: Heart,
  pill: Pill,
  droplets: Droplets,
  'shopping-cart': ShoppingCart,
  wallet: Wallet,
  house: House,
  car: Car,
  plane: Plane,
  dog: Dog,
  leaf: Leaf,
  music: Music,
  palette: Palette,
  brush: Brush,
  'gamepad-2': Gamepad2,
  gift: Gift,
  star: Star,
  sparkles: Sparkles,
  flame: Flame,
  zap: Zap,
}

export const DEFAULT_ICON = 'list-todo'

/** Renders a stored icon: a known lucide name, otherwise the text itself (an emoji). */
export function TaskIcon({ icon, className }: { icon: string | null; className?: string }) {
  const name = icon ?? DEFAULT_ICON
  const Icon = TASK_ICONS[name]
  if (Icon) return <Icon aria-hidden="true" className={cn('size-5', className)} />
  return (
    <span aria-hidden="true" className={cn('text-lg leading-none', className)}>
      {name}
    </span>
  )
}
